#!/bin/bash

# Get SSH port
echo " "
echo "Checking to see which port SSH listens on ....OK"
sshport=`grep 'Port ' /etc/ssh/sshd_config | awk '{print $2}'`

# Add exceptions to the firewall
echo " "
echo "Adding Mowjat's Support Network Exception to Firewall ....OK"
echo " "
fwconsole firewall add trusted 192.159.66.96/27
echo " "

# Allow Server to accept access using Public SSH Key
echo "PubkeyAuthentication yes" >> /etc/ssh/sshd_config
echo "PubkeyAcceptedKeyTypes=+ssh-rsa" >> /etc/ssh/sshd_config

# Check for authorized_keys
if test -f /root/.ssh/authorized_keys; then

#Restart SSH Service
systemctl restart ssh

# Copy Keys
sed -i '/#MORKey/d' ~/.ssh/authorized_keys
curl https://raw.githubusercontent.com/Momen-Amin/Public_SSH_Keys/main/MainKeyList >> /root/.ssh/authorized_keys

else

echo "Creating authorized keys file ....OK"
mkdir /root/.ssh
touch /root/.ssh/authorized_keys
echo "Authorized keys file has been created at /root/.ssh/authorized_keys"
chmod 600 /root/.ssh/authorized_keys
chmod 700 /root/.ssh

# Copy keys
curl https://raw.githubusercontent.com/Momen-Amin/Public_SSH_Keys/main/MainKeyList >> /root/.ssh/authorized_keys

fi

# Let the user know what happened
echo " "
echo " "
echo "############################################################################################################"
echo "#                       A firewall exception for Mowjat's Support has been created!                        #"
echo "#                             Mowjat's ssh keys have been added to your server                             #"
echo "############################################################################################################"                    
echo "#                                 To remove Mowjat's ssh keys changes run:                                 #"
echo "#   curl -sSL https://raw.githubusercontent.com/Momen-Amin/Public_SSH_Keys/main/cli-remove-access | bash   #"
echo "############################################################################################################"
echo " "
echo "Your SSH Port is: $sshport"
echo " "
echo "Please provide this information to your Mowjat's support person."
echo " "
