#!/bin/bash

# Remove SSH Key
sed -i '/#MORKey/d' ~/.ssh/authorized_keys
echo " "
echo "Removing Mowjat's SSH Key from your system is in progress...."
echo " "
echo "Mowjat's SSH Key has been removed from your system successfully."
echo " "
